import { expandEnergyShorthand, isBasicEnergyName } from "./energy.js";
import {
  inferFormat,
  isCardLine,
  isSectionLine,
  isTotalLine,
  looksLikeDecklist,
  splitCardTokens,
} from "./lines.js";
import type {
  CardCategory,
  DeckFormat,
  ParseOptions,
  ParseWarning,
  ParsedCard,
  ParsedDeck,
} from "./types.js";

export function detectFormat(text: string): DeckFormat | "unknown" {
  if (!looksLikeDecklist(text)) return "unknown";
  return inferFormat(text);
}

export function parseDecklist(text: string, options: ParseOptions = {}): ParsedDeck {
  const format =
    options.format && options.format !== "auto"
      ? options.format
      : inferFormat(text);

  const cards: ParsedCard[] = [];
  const warnings: ParseWarning[] = [];
  const sectionCounts: ParsedDeck["sectionCounts"] = {};
  let declaredTotal: number | undefined;
  let currentCategory: CardCategory = "unknown";

  const lines = text.split(/\r?\n/);
  for (let i = 0; i < lines.length; i++) {
    const lineNumber = i + 1;
    const raw = lines[i] ?? "";
    const line = raw.replace(/^[\s*•-]+/, "").trim();
    if (!line) continue;

    const section = isSectionLine(line);
    if (section) {
      currentCategory = section.category;
      if (section.count !== undefined) {
        sectionCounts[section.category === "unknown" ? "trainer" : section.category] =
          section.count;
      }
      continue;
    }

    const total = isTotalLine(line);
    if (total !== undefined) {
      declaredTotal = total;
      continue;
    }

    const cardLine = isCardLine(line);
    if (!cardLine) {
      if (!isIgnorableHeader(line)) {
        warnings.push({
          line: lineNumber,
          message: `Ignored line: "${line}"`,
        });
      }
      continue;
    }

    const split = splitCardTokens(cardLine.rest);
    const name = expandEnergyShorthand(split.nameTokens.join(" ")).trim();
    if (!name) {
      warnings.push({ line: lineNumber, message: `No card name on line: "${line}"` });
      continue;
    }

    let category = currentCategory;
    if (category === "unknown") {
      category = isBasicEnergyName(name) ? "energy" : "unknown";
    }

    cards.push({
      quantity: cardLine.quantity,
      name,
      setCode: split.setCode,
      number: split.number,
      foil: split.foil,
      category,
      line: lineNumber,
      raw: line,
    });
  }

  const totalCards = cards.reduce((sum, card) => sum + card.quantity, 0);
  if (declaredTotal !== undefined && declaredTotal !== totalCards) {
    warnings.push({
      message: `Export says "Total Cards: ${declaredTotal}" but parsed counts sum to ${totalCards}.`,
    });
  }

  return {
    format,
    cards,
    totalCards,
    declaredTotal,
    sectionCounts: Object.keys(sectionCounts).length ? sectionCounts : undefined,
    warnings,
  };
}

function isIgnorableHeader(line: string): boolean {
  return (
    /^\*+/.test(line) ||
    /deck list/i.test(line) ||
    /pokemon\.com/i.test(line) ||
    /generated by/i.test(line)
  );
}
